# These pre-commit hooks don't ensure a passing CI run. Instead they act as
# a quick "smoke check" running static code analysis on the files changed.
# The hooks do NOT:
#     - Run tests or other time-consuming tasks.
#     - Check the whole codebase, just modified files.
#     - Let mypy access dependencies' typehints.
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: e1668fe86af3810fbca72b8653fe478e66a0afdc  # frozen: v3.2.0
  hooks:
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/timothycrosley/isort
  rev: 377d260ffa6f746693f97b46d95025afc4bd8275  # frozen: 5.4.2
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: e66be67b9b6811913470f70c28b4d50f94d05b22  # frozen: 20.8b1
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: d6e31aeb109d8ff85282c3fd632c89f8ea7b0dee  # frozen: v0.782
  hooks:
  - id: mypy
    args:
    # Suppress errors resulting from no access to dependencies
    - --ignore-missing-imports
    - --no-warn-unused-ignores
    # Allow multiple scripts (no .py postfix in name) to be checked in a single mypy invocation
    - --scripts-are-modules
- repo: https://gitlab.com/pycqa/flake8
  rev: 05f6544aef321e2fee03a1277ce2eef8880fb927  # frozen: 3.8.3
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/myint/docformatter
  rev: de0bf8fa254d25a01383fecdb6335bea01daeae3  # frozen: v1.3.1
  hooks:
  - id: docformatter
