repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0  # frozen: v4.3.0
  hooks:
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 6f51a66bba59954917140ec2eeeaa4d5e630e6ce  # frozen: v1.9.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
- repo: https://github.com/PyCQA/isort
  rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 27d20144a7517594e24a1649451177b2a11284be  # frozen: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 0b037c2b59aa62dc3be3287d175295f1a5547eb9  # frozen: v0.991
  hooks:
  - id: mypy
    args:
    # Allow multiple scripts (no .py postfix in name) to be checked in a single mypy invocation
    - --scripts-are-modules
    additional_dependencies:
    - graypy
- repo: https://github.com/PyCQA/flake8
  rev: f8e1b317742036ff11ff86356fd2b68147e169f7  # frozen: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/myint/docformatter
  rev: 8b8dae1d990e2e4fec7ff6704a79c23a403cd605  # frozen: v1.5.0
  hooks:
  - id: docformatter
- repo: https://github.com/executablebooks/mdformat
  rev: 82f84976fc57d5ae61cbf2d457a26a89d4b4eef4  # frozen: 0.7.16
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-black
    - mdformat-toc
