repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 6e2418c5521b7d606e72914dced3253f9ace1205  # frozen: v3.4.0
  hooks:
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: eccb8cef2c7987014012c3f07be550415c4d379e  # frozen: v1.7.1
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
- repo: https://github.com/timothycrosley/isort
  rev: 473d150c1db60f4614a574e30993e9e0d3ca0cce  # frozen: 5.7.0
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: e66be67b9b6811913470f70c28b4d50f94d05b22  # frozen: 20.8b1
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 59a8e37f2ab16103e56845983e9a5900facfa856  # frozen: v0.800
  hooks:
  - id: mypy
    args:
    # Allow multiple scripts (no .py postfix in name) to be checked in a single mypy invocation
    - --scripts-are-modules
    additional_dependencies:
    - graypy
- repo: https://gitlab.com/pycqa/flake8
  rev: bb6a530e28acab8d3551043b3e8709db8bcbac6b  # frozen: 3.8.4
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/myint/docformatter
  rev: 67919ee01837761f2d954d7fbb08c12cdd38ec5a  # frozen: v1.4
  hooks:
  - id: docformatter
- repo: https://github.com/executablebooks/mdformat
  rev: f70155cd5aec40cdc911f1e5c3ac16f28d5ab0ba  # frozen: 0.5.6
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-black
    - mdformat-toc
